version: 2.1


# use orbs when it is available in circleci orb market
# passing few paramters in orb will also do the job

#orbs:
#    cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
        - image: circleci/node:latest
          auth:
            username: gamersinstinct7
            password: $DOCKERHUB_PASSWORD
    steps:
        - checkout
        - restore_cache:
            keys:
                # cache will auto invalidate if package.json changers
                # change to v2/v3 if you need to forcefully install the dependencies
                # changing this will build a new cache
                # also change at save_cache step
                - v3-deps-{{checksum "package-lock.json"}}
        - run:
            name: Install dependencies
            command: |
                npm install
                # `npm ci` command will install all the dependencies again
                # `npm install` will install only those which are not installed (also better to use this to install missing dependencies)

        - save_cache:
            paths:
                - node_modules
            key: v3-deps-{{checksum "package-lock.json"}}
        - run:
            name: run Next.JS build
            command: npm run deploy
        - run:
            name: print all contents at the current working directory
            command: ls -a
        - persist_to_workspace:
              root: .
              paths:
                  - '*'
        - store_artifacts:
            path: .next/analyze/server.html
        - store_artifacts:
            path: .next/analyze/client.html

  test:
    docker:
        - image: cypress/browsers
          auth:
            username: gamersinstinct7
            password: $DOCKERHUB_PASSWORD
    steps:
        - attach_workspace:
            at: .
        - restore_cache:
            key: cy-bin-v1-{{arch}}
        - run:
            name: install cypress if verification fails
            command: npx cypress install
        - save_cache:
            paths:
                - /root/.cache/Cypress
            key: cy-bin-v1-{{arch}}
        - run:
            name: verify cypress
            command: npx cypress verify
            when: always
        - run:
            # starting the server on a different step does not work
            name: run cypress tests
            command: npm run ci:test
        - store_artifacts:
            path: cypress/videos
        

workflows:
    build_and_test:
        jobs:
            - build:
                context:
                    - Docker
            - test:
                requires:
                    - build
                context:
                    - Docker