version: 2.1

jobs:
  run_build:
    docker:
        - image: circleci/node:latest
    steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
                npm ci
        - run:
            name: Build NEXT.JS
            command: |
                npm run build
        - run:
            name: Check export possible
            command: |
                npm run export
workflows:
    build_app:
        jobs:
            - run_build

#orbs:
#   node: circleci/node@3.0.0
#workflows:
#  node-tests:
#    jobs:
#      - node/test
