name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false 

      - name: Get Node
        uses: actions/setup-node@v1

      - name: Build and Deploy
        run: |
          npm ci
          npm run deploy
          touch portfolio/.nojekyll
        env:
            NODE_ENV: production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: portfolio
          CLEAN: true