name: Netlify Build and Deploy Main

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Node
        uses: actions/setup-node@v1

      - name: Build and Deploy
        run: |
          npm ci
          npm run deploy
        env:
            NODE_ENV: production

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './portfolio'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploying at aditya-mitra.netlify.app - ${{ github.event.head_commit.message }}"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_V2 }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_V2 }}
        timeout-minutes: 1