name: Build_and_Deploy_Main

on:
    push
    pull_request

jobs:
    setup_build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Get Node
              uses: actions/setup-node@v1

            - name: Install dependencies
              run: |
                  npm ci

            - name: Build
              run: |
                  npm run ci:build

            - name: Cache all of the above
              uses: actions/cache@v2
              id: cache-p
              with:
                  path: ./*
                  key: ${{github.sha}}